import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from '../Components/ui/toaster'

const inter = Inter({ subsets: ["latin"] });

import { Plus_Jakarta_Sans } from 'next/font/google'

// Custom Font from Google.
const plusJakartaSansBold = Plus_Jakarta_Sans({
    subsets : ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={`${plusJakartaSansBold.className}`}>
          {children}
          <Toaster />
        </body>
    </html>
  );
}
